"""initial schema: users, businesses, registrations, regulations, obligations, filings

Revision ID: 0001
Revises:
Create Date: 2026-08-19

Hand-written rather than autogenerated: Docker/Postgres was unavailable in
this environment, and `alembic revision --autogenerate` requires a live DB
connection to introspect against. Column types/constraints are written to
match backend/app/models/ exactly.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.domain.enums import (
    BusinessLegalType,
    FilingStatus,
    ObligationApplicability,
    ObligationFrequency,
    ObligationStatus,
    ObligationType,
    RegistrationStatus,
    RegistrationType,
    SectorType,
    TurnoverBand,
    UserRole,
)

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "businesses",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("sector", sa.Enum(SectorType, native_enum=False, length=20), nullable=False),
        sa.Column("state", sa.String(100), nullable=False),
        sa.Column(
            "registration_type", sa.Enum(BusinessLegalType, native_enum=False, length=20), nullable=False
        ),
        sa.Column("turnover_band", sa.Enum(TurnoverBand, native_enum=False, length=20), nullable=False),
        sa.Column("employee_count", sa.Integer(), nullable=False),
        sa.Column("incorporation_date", sa.Date(), nullable=True),
        sa.Column("udyam_number", sa.String(50), nullable=True),
        sa.Column("gstin", sa.String(20), nullable=True),
        sa.Column("pan", sa.String(20), nullable=True),
        sa.Column("address", sa.String(500), nullable=True),
        sa.Column("contact_phone", sa.String(20), nullable=True),
        sa.Column("contact_email", sa.String(255), nullable=True),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("role", sa.Enum(UserRole, native_enum=False, length=20), nullable=False),
        sa.Column(
            "business_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "registrations",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "business_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("type", sa.Enum(RegistrationType, native_enum=False, length=30), nullable=False),
        sa.Column("number", sa.String(100), nullable=True),
        sa.Column("status", sa.Enum(RegistrationStatus, native_enum=False, length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("document_ref", sa.String(500), nullable=True),
        sa.UniqueConstraint("business_id", "type", name="uq_registration_business_type"),
    )

    op.create_table(
        "regulations",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("code", sa.String(50), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("authority", sa.String(255), nullable=False),
        sa.Column("jurisdiction", sa.String(50), nullable=False),
        sa.Column("applicability_rules", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(500), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("version", sa.String(20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.UniqueConstraint("code", name="uq_regulations_code"),
    )
    op.create_index("ix_regulations_code", "regulations", ["code"])

    op.create_table(
        "obligations",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "business_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("regulation_id", sa.Uuid(as_uuid=True), sa.ForeignKey("regulations.id"), nullable=False),
        sa.Column("rule_id", sa.String(100), nullable=False),
        sa.Column("obligation_type", sa.Enum(ObligationType, native_enum=False, length=20), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "frequency", sa.Enum(ObligationFrequency, native_enum=False, length=20), nullable=True
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "applicability",
            sa.Enum(ObligationApplicability, native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum(ObligationStatus, native_enum=False, length=20), nullable=False
        ),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("business_id", "rule_id", name="uq_obligation_business_rule"),
    )
    op.create_index("ix_obligations_rule_id", "obligations", ["rule_id"])

    op.create_table(
        "filings",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "obligation_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("obligations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("period", sa.String(20), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Enum(FilingStatus, native_enum=False, length=20), nullable=False),
        sa.Column(
            "human_approved_by",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("document_ref", sa.String(500), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("filings")
    op.drop_index("ix_obligations_rule_id", table_name="obligations")
    op.drop_table("obligations")
    op.drop_index("ix_regulations_code", table_name="regulations")
    op.drop_table("regulations")
    op.drop_table("registrations")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_table("businesses")
