import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import Nav from '../components/Nav'
import { listObligations, updateObligationStatus } from '../lib/api'
import type { Obligation, ObligationStatus } from '../types'

type FilterKey = 'all' | 'due_soon' | 'overdue' | 'completed'

const FILTERS: { key: FilterKey; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'due_soon', label: 'Due soon' },
  { key: 'overdue', label: 'Overdue' },
  { key: 'completed', label: 'Completed' },
]

const STATUS_STYLES: Record<ObligationStatus, string> = {
  pending: 'bg-slate-100 text-slate-600',
  due_soon: 'bg-amber-100 text-amber-700',
  overdue: 'bg-red-100 text-red-700',
  completed: 'bg-emerald-100 text-emerald-700',
}

export default function Checklist() {
  const { businessId } = useParams<{ businessId: string }>()
  const [obligations, setObligations] = useState<Obligation[]>([])
  const [filter, setFilter] = useState<FilterKey>('all')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!businessId) return
    listObligations(businessId)
      .then(setObligations)
      .finally(() => setLoading(false))
  }, [businessId])

  const visible = useMemo(() => {
    const relevant = obligations.filter((o) => o.applicability !== 'not_applicable')
    if (filter === 'all') return relevant
    return relevant.filter((o) => o.status === filter)
  }, [obligations, filter])

  async function markCompleted(obligation: Obligation) {
    const updated = await updateObligationStatus(obligation.id, 'completed')
    setObligations((prev) => prev.map((o) => (o.id === updated.id ? updated : o)))
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <Nav />
      <main className="mx-auto max-w-5xl px-6 py-10">
        <h1 className="mb-1 text-xl font-semibold">Compliance Checklist</h1>
        <p className="mb-6 text-sm text-slate-500">
          Every obligation below is generated by the deterministic Rules Engine, with a
          citation back to its source regulation -- not by the LLM.
        </p>

        <div className="mb-6 flex gap-2">
          {FILTERS.map((f) => (
            <button
              key={f.key}
              onClick={() => setFilter(f.key)}
              className={`rounded-full px-3 py-1.5 text-sm font-medium ${
                filter === f.key ? 'bg-slate-900 text-white' : 'bg-white text-slate-600 border border-slate-200'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>

        {loading ? (
          <p className="text-sm text-slate-500">Loading…</p>
        ) : visible.length === 0 ? (
          <p className="text-sm text-slate-400">No obligations in this view.</p>
        ) : (
          <ul className="space-y-3">
            {visible.map((o) => (
              <li key={o.id} className="rounded-lg border border-slate-200 bg-white p-5">
                <div className="mb-2 flex items-start justify-between gap-4">
                  <div>
                    <p className="font-medium">{o.title}</p>
                    <p className="text-xs text-slate-400">
                      {o.obligation_type} · {o.frequency ?? 'one-time'}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {o.applicability === 'review_required' && (
                      <span className="rounded-full bg-violet-100 px-2 py-0.5 text-xs font-medium text-violet-700">
                        Needs review
                      </span>
                    )}
                    <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_STYLES[o.status]}`}>
                      {o.status.replace('_', ' ')}
                    </span>
                  </div>
                </div>

                <p className="mb-2 text-sm text-slate-600">{o.reason}</p>

                <p className="mb-3 text-xs text-slate-400">
                  Source:{' '}
                  <a
                    href={o.regulation_source_url}
                    target="_blank"
                    rel="noreferrer"
                    className="underline hover:text-slate-600"
                  >
                    {o.regulation_title}
                  </a>
                </p>

                <div className="flex items-center justify-between text-xs text-slate-400">
                  <span>Due: {o.due_date ?? '—'}</span>
                  {o.status !== 'completed' && (
                    <button
                      onClick={() => markCompleted(o)}
                      className="rounded-md border border-slate-300 px-2 py-1 text-slate-600 hover:bg-slate-50"
                    >
                      Mark completed
                    </button>
                  )}
                </div>
              </li>
            ))}
          </ul>
        )}
      </main>
    </div>
  )
}
